[package]
name = "bft-json-crdt"
version = "0.1.0"
edition = "2021"

[dependencies]
splay_tree = "0.2.10"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

