[package]
name = "bft-json-crdt"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.11.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

